import imageIcon from "../../assets/specialityImg1.jpg";
const SpecialitiesData =[  {
    "id": 1,
    "title": "Root Canal Treatment",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vitae a ut turpis sit enim tempor. Nisl sit vitae, risus duis varius adipiscing tristique. Viverra sed posuere sed vel mollis viverra. Turpis posuere ac quis nulla fringilla amet.",
    "image": imageIcon,
    "averageCost":5500,
    "averageOperationTime":3,
    "successfulOperations":200,
  },
  {
    "id": 2,
    "title": "Teeth Alighnment",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vitae a ut turpis sit enim tempor. Nisl sit vitae, risus duis varius adipiscing tristique. Viverra sed posuere sed vel mollis viverra. Turpis posuere ac quis nulla fringilla amet.",
    "image": imageIcon,
    "averageCost":8000,
    "averageOperationTime":6,
    "successfulOperations":320,
  },
  {
    "id": 3,
    "title": "Regular Monitored Checkups",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vitae a ut turpis sit enim tempor. Nisl sit vitae, risus duis varius adipiscing tristique. Viverra sed posuere sed vel mollis viverra. Turpis posuere ac quis nulla fringilla amet.",
    "image": imageIcon,
    "averageCost":1000,
    "averageOperationTime":1,
    "successfulOperations":1300,
  },
  {
    "id": 4,
    "title": "Teeth Removal",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vitae a ut turpis sit enim tempor. Nisl sit vitae, risus duis varius adipiscing tristique. Viverra sed posuere sed vel mollis viverra. Turpis posuere ac quis nulla fringilla amet.",
    "image": imageIcon,
    "averageCost":6300,
    "averageOperationTime":5,
    "successfulOperations":400,
  },
  {
    "id": 5,
    "title": "Cosmetic Surgeries",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vitae a ut turpis sit enim tempor. Nisl sit vitae, risus duis varius adipiscing tristique. Viverra sed posuere sed vel mollis viverra. Turpis posuere ac quis nulla fringilla amet.",
    "image": imageIcon,
    "averageCost":25000,
    "averageOperationTime":10,
    "successfulOperations":145,
  },
  {
    "id": 6,
    "title": "Root Canal Treatment",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vitae a ut turpis sit enim tempor. Nisl sit vitae, risus duis varius adipiscing tristique. Viverra sed posuere sed vel mollis viverra. Turpis posuere ac quis nulla fringilla amet.",
    "image": imageIcon,
    "averageCost":5500,
    "averageOperationTime":3,
    "successfulOperations":200,
  },
  {
    "id": 7,
    "title": "Teeth Alighnment",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vitae a ut turpis sit enim tempor. Nisl sit vitae, risus duis varius adipiscing tristique. Viverra sed posuere sed vel mollis viverra. Turpis posuere ac quis nulla fringilla amet.",
    "image": imageIcon,
    "averageCost":8000,
    "averageOperationTime":6,
    "successfulOperations":320,
  },
  {
    "id": 8,
    "title": "Regular Monitored Checkups",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vitae a ut turpis sit enim tempor. Nisl sit vitae, risus duis varius adipiscing tristique. Viverra sed posuere sed vel mollis viverra. Turpis posuere ac quis nulla fringilla amet.",
    "image": imageIcon,
    "averageCost":1000,
    "averageOperationTime":1,
    "successfulOperations":1300,
  },
]

export default SpecialitiesData;
